src/IJS.ts, src/filters/__tests__/invert.test.ts, src/filters/blur.ts, src/filters/invert.ts, src/operations/__tests__/grey.test.ts, src/operations/convertColor.ts, src/operations/grey.ts, src/operations/greyAlgorithms.ts, src/operations/index.ts
- feat: copy grey from image-js
- fix: fix all errors in greyAlgorithms
- docs: write grey algorithms docs
- fix: working on grey
- fix: fix grey clamp problem
- fix: fix all errors in grey
- test: fixing some of the grey test errors
- test: adapt invert test to new syntax
- test: add RGBA test for blur
- fix: invert had problem with alpha
- docs: add blur function doc
- feat: export copyAlpha from convertColors
- feat: add geometry methods to IJS
- fix: make options optional
- fix: keepAlpha option had a bugf
- fix: grey is working (#8)
=> Migrate grey algorithms

package.json, src/IJS.ts, src/compute/__tests__/histogram.test.ts, src/compute/histogram.ts, src/operations/threshold.ts, src/operations/thresholds/__tests__/thresholdAlgorithms.test.ts, src/operations/thresholds/huang.ts, src/operations/thresholds/intermodes.ts, src/operations/thresholds/isodata.ts, src/operations/thresholds/li.ts, src/operations/thresholds/maxEntropy.ts, src/operations/thresholds/mean.ts, src/operations/thresholds/minError.ts, src/operations/thresholds/minimum.ts, src/operations/thresholds/moments.ts, src/operations/thresholds/otsu.ts, src/operations/thresholds/percentile.ts, src/operations/thresholds/renyiEntropy.ts, src/operations/thresholds/shanbhag.ts, src/operations/thresholds/triangle.ts, src/operations/thresholds/yen.ts, tsconfig.json
- feat: copy all thresholds from image-js
- foc: add computeThreshold tsdoc
- fix: migrating all thresholds to ts syntax
- fix: change histogram return type
- fix: make histogram a uint32 array
- feat: add all algorithms to threshold
- chore: remove useless comments
- test: add thresholds test
- test: fix histogram test
=> Migrate threshold algorithms

src/roi/RoiManager.ts, src/roi/RoiMapManager.ts, src/roi/__tests__/fromMask.test.ts, src/roi/fromMask.ts, src/roi/index.ts
- feat: define roiManager class
- feat: start RoiMarManager class
- feat: start migrating fromMask
- fix(fromMask): change getBitXY to getBit
- fix(fromMask): remove all visible errors
- feat(getMapMatrix): function for easier testing
- test(fromMask): old tests are passing
- test(fromMask): complete
=> Migrate `fromMask()`

.github/workflows/release-head.yml, package.json
- chore: setup exports field correctly
- chore: add release-head workflow
=> release head

demo/components/Home.tsx, demo/components/testFunctions/testExtract.ts, src/IJS.ts, src/operations/__tests__/extract.test.ts, src/operations/extract.ts, src/operations/index.ts
- feat: implement extract
- docs: add extract demo
- docs: add testExtractRoi to demo
=> Implement `extract()`

src/IJS.ts, src/filters/__tests__/flip.test.ts, src/filters/__tests__/flipX.test.ts, src/filters/__tests__/flipY.test.ts, src/filters/flip.ts, src/filters/flipX.ts, src/filters/flipY.ts
closes : https://github.com/image-js/image-js-typescript/issues/56
=> feat: Flip

src/utils/getOutputImage.ts
=> Fix getOutPutImage

src/IJS.ts, src/draw/__tests__/drawLine.test.ts, src/draw/drawLine.ts, src/draw/index.ts, src/paint/index.ts
closes : https://github.com/image-js/image-js-typescript/issues/94
=> chore: rename paintLine to drawLine

src/draw/__tests__/drawPoints.test.ts, src/draw/__tests__/drawPolygonOnIjs.test.ts, src/draw/__tests__/drawPolygonOnMask.test.ts, src/draw/__tests__/drawPolylineOnMask.test.ts, src/draw/__tests__/drawRectangle.test.ts
closes: https://github.com/image-js/image-js-typescript/issues/118
=> draw outside images tests

src/__tests__/Image.test.ts, src/operations/__tests__/threshold.test.ts, src/operations/threshold.ts, src/utils/validators.ts
=> feat(threshold): authorize threshold in percents

demo/components/Home.tsx, demo/components/testFunctions/testGetFeret.ts, jest.setup.ts, src/Mask.ts, src/maskAnalysis/__tests__/getConvexHull.test.ts, src/maskAnalysis/__tests__/getFeret.test.ts, src/maskAnalysis/getConvexHull.ts, src/maskAnalysis/getFeret.ts, src/maskAnalysis/index.ts, src/maskAnalysis/utils/__tests__/getAngle.test.ts, src/maskAnalysis/utils/__tests__/getMbrFromPoints.test.ts, src/maskAnalysis/utils/getAngle.ts, src/maskAnalysis/utils/getMbrAngle.ts, src/maskAnalysis/utils/getMbrFromPoints.ts, src/roi/Roi.ts, src/utils/geometry/__tests__/polygons.test.ts, src/utils/geometry/polygons.ts
- fix(Roi): make map readonly
- refactor: move getAngle to own file
- feat: implement getFeret
- docs: document feret interfaces
- fix: getPolygonArea returned negative values
- fix: convex Hull
- wip: working on getFeret
- test: enhance feret test
- test(getFeret): all tests pass except one
- docs(demo): add getFeret demo
- test(getFeret): all tests are good
=> Implement Feret diameters on Mask

src/geometry/__tests__/rotate.test.ts, src/load/readImg.ts, src/operations/thresholds/__tests__/thresholdAlgorithms.test.ts, src/save/writeCanvas.ts, src/utils/__tests__/interpolateBorder.test.ts, src/utils/geometry/lines.ts
- refactor: remove useless line utils
- test: enhance interpolation coverage
- test: enhance thresholds coverage
- chore: add todo comments
=> Enhance coverage

demo/components/CameraSnapshotButton.tsx, demo/components/CameraTransform.tsx, demo/components/Home.tsx, demo/components/SnapshotImage.tsx, demo/components/comparisonFunctions/testComputeSsim.ts, demo/components/testFunctions/testComputeSsim.ts
- feat: add CameraSnapshotButton and SnapshotImage
- feat: implement CameraSnapshotButton
- feat: implement SnapshotImage
- feat: adapt demo to use snapshot
- docs: ssim demo works
=> Add snapshot to demo

src/Image.ts, src/__tests__/Image.test.ts, src/featureMatching/getBriefDescriptors.ts, src/featureMatching/utils/__tests__/getGaussianPoints.test.ts, src/geometry/__tests__/rotate.test.ts, src/geometry/rotate.ts, src/geometry/transform.ts
- refactor: getCoordinates point format
- refactor: getRotationMatrix point format
- refactor: rotate point format
=> Refactor wrong point format

src/featureMatching/__tests__/getIntensityMoment.test.ts, src/featureMatching/getIntensityMoment.ts
=> fix: generalize getIntensityMoment

src/Image.ts, src/Mask.ts, src/__tests__/Image.test.ts, src/__tests__/Mask.test.ts, src/featureMatching/getFastScore.ts, src/featureMatching/isFastKeypoint.ts, src/featureMatching/utils/compareIntensity.ts
=> feat: add functions to get and set by point

src/save/__tests__/write.test.ts, src/save/write.ts
Closes: https://github.com/image-js/image-js-typescript/issues/163
=> feat: add support for URL and recursive option in write methods

src/roi/__tests__/fromMask.test.ts
close: https://github.com/image-js/image-js-typescript/issues/287
=> test: fromMask of image containing only '1' or '0'

src/utils/constants/__tests__/channelLabels.test.ts, src/utils/constants/channelLabels.ts
=> feat: implement channelLabels

demo/components/testFunctions/testGetConvexHull.ts, demo/components/testFunctions/testGetFeret.ts, demo/components/testFunctions/testGetMbr.ts, demo/components/testFunctions/testPaintMask.ts, src/maskAnalysis/__tests__/getMbr.test.ts, src/operations/__tests__/threshold.test.ts, src/operations/threshold.ts, src/roi/__tests__/RoiMapManager.test.ts
=> fix: handle 0 to 1 threshold

src/roi/Roi.ts, src/roi/__tests__/borderLengths.test.ts, src/roi/__tests__/perimeter.test.ts
close: https://github.com/image-js/image-js-typescript/issues/262
=> chore: change externalIDs and borderIDs into arrays of objects with id and length properties

src/operations/__tests__/convertColor.test.ts, src/operations/convertColor.ts, src/save/writeCanvas.ts
This enables the writeCanvas method for masks
=> feat: allow conversion from mask to RGB and RGBA

src/save/writeCanvas.ts
Fixes: https://github.com/image-js/image-js-typescript/issues/25
Fixes: https://github.com/image-js/image-js-typescript/issues/325
=> fix: allow 16 bits images to be written on canvas

src/Image.ts, src/__tests__/Image.test.ts
close: https://github.com/image-js/image-js-typescript/issues/340
=> feat: add getRow and getColumn methods to Image.ts

src/roi/Roi.ts
close: https://github.com/image-js/image-js-typescript/issues/265
=> chore: make computeIndex private

src/roi/Roi.ts
close: https://github.com/image-js/image-js-typescript/issues/272
=> chore: simplify ROI code 

package.json, src/load/readImg.ts, src/roi/Roi.ts
close: https://github.com/image-js/image-js-typescript/issues/316
=> docs: improve roi comments

src/compute/__tests__/histogram.test.ts, src/compute/histogram.ts
close: https://github.com/image-js/image-js-typescript/issues/357
=> feat: improve histogram

scripts/alignImages/alignImages.ts, src/align/affineTransfrom/getAffineTransform.ts, src/align/affineTransfrom/utils/__tests__/getSourceWithoutMargins.test.ts, src/align/affineTransfrom/utils/getSourceWithoutMargins.ts
=> feat(getAffineTransform): simplify options

src/filters/__tests__/gaussianBlur.test.ts, src/filters/gaussianBlur.ts
close: https://github.com/image-js/image-js-typescript/issues/326
=> refactor: add additional error handling for sigma option and a test case

src/align/__tests__/alignMinDifference.test.ts, src/align/alignMinDifference.ts, src/compare/subtract.ts
Improve the speed of alignMinDifference.
Original code: 1700 ms
Avoiding the creation of images: 1200 ms
Changing Math.abs to if / else : 200 ms
=> chore: improve alignMinDifference

src/Mask.ts, src/__tests__/Mask.test.ts, src/align/__tests__/alignMinDifference.test.ts, src/align/alignMinDifference.ts
- feat: alignMinDifference returns the similarity
- feat: add getNbNonZeroPixels method in Mask
=> similarity

src/__tests__/Image.test.ts, src/draw/__tests__/drawPolygonOnImage.test.ts, src/utils/validators/validators.ts
=> fix: channel validator

src/align/__tests__/alignMinDifference.test.ts, src/align/alignMinDifference.ts, src/filters/__tests__/autoLevel.test.ts, src/filters/autoLevel.ts
=> feat(alignMinDiff): extend to any nb of components

src/filters/__tests__/hypotenuse.test.ts, src/filters/hypotenuse.ts
close: https://github.com/image-js/image-js-typescript/issues/406
=> fix: fix the bug with hypotenuse custom channels

src/operations/__tests__/threshold.test.ts, src/operations/threshold.ts, src/operations/thresholds/__tests__/thresholdAlgorithms.test.ts, src/roi/__tests__/waterShed.test.ts
=> feat: add option to specify the number of slots for the histogram

src/operations/__tests__/threshold.test.ts, src/operations/threshold.ts
=> fix: scale threshold when slots number is changed

src/operations/__tests__/convertBitDepth.test.ts, src/operations/convertBitDepth.ts, src/save/__tests__/encodeBmp.test.ts, src/save/__tests__/encodePng.test.ts, src/save/encodeBmp.ts, src/save/encodeJpeg.ts, src/save/encodePng.ts, src/save/write.ts
close: https://github.com/image-js/image-js-typescript/issues/464
=> refactor: move automatic conversion from write to encode

src/index.ts
close: https://github.com/image-js/image-js-typescript/issues/474
=> feat: add Stack class to public API
